name: Run Feature Engineering Notebook Daily

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 12 PM SAST (UTC+2)
  workflow_dispatch:     # Optional: Allows manual run from GitHub UI

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install notebook nbconvert papermill

      - name: Run the notebook
        run: |
          papermill Funeral_Cover_Feature_Engineering.ipynb output.ipynb
